#!/usr/bin/env sh

export PATH="/opt/homebrew/bin:$PATH"

if [ -d "$HOME/.nvm/versions/node" ]; then
  latest_node_dir=$(find "$HOME/.nvm/versions/node" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)

  if [ -n "$latest_node_dir" ]; then
    export PATH="$latest_node_dir/bin:$PATH"
  fi
fi

lint-staged
